### ISSUE TITLE
Translation checklist

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/RRTMGP.jl#30]
ck = Charlie Kawczynski
sk = Sriharsha Kandala

# Examples
 - [x] sk  237      examples\mo_load_coefficients.F90
 - [x] sk  308      examples\rfmip-clear-sky\rrtmgp_rfmip_lw.F90
 - [x] ck  354      examples\rfmip-clear-sky\rrtmgp_rfmip_sw.F90
 - [x] sk  422      examples\mo_simple_netcdf.F90
 - [x] sk  453      examples\rfmip-clear-sky\mo_rfmip_io.F90

# RRTMGP
 - [x] ck  45       rrtmgp\mo_util_reorder.F90
 - [x] sk  61       rrtmgp\kernels\mo_reorder_kernels.F90
 - [x] ck  65       rrtmgp\mo_rrtmgp_constants.F90
 - [x] ck  87       rrtmgp\mo_util_string.F90
 - [x] ck  106      rrtmgp\mo_gas_optics.F90
 - [x] ck  393      rrtmgp\mo_gas_concentrations.F90
 - [x] ck  773      rrtmgp\kernels\mo_gas_optics_kernels.F90
 - [x] ck  1757     rrtmgp\mo_gas_optics_rrtmgp.F90

# RTE
 - [x] sk   110      rte\kernels\mo_fluxes_broadband_kernels.F90
 - [x] ck   201      rte\mo_fluxes.F90
 - [x] sk   230      rte\mo_rte_sw.F90
 - [x] sk   230      rte\mo_util_array.F90
 - [x] sk   273      rte\mo_rte_lw.F90
 - [x] ck   280      rte\mo_source_functions.F90
 - [x] sk   693      rte\kernels\mo_optical_props_kernels.F90
 - [x] ck   951      rte\kernels\mo_rte_solver_kernels.F90
 - [x] ck   1169     rte\mo_optical_props.F90

# Extensions
 - [ ] --  51       extensions\mo_heating_rates.F90
 - [x] --  88       extensions\mo_fluxes_byband_kernels.F90
 - [ ] --  106      extensions\mo_fluxes_bygpoint.F90
 - [ ] --  158      extensions\mo_fluxes_byband.F90
 - [ ] --  247      extensions\mo_compute_bc.F90
 - [ ] --  308      extensions\cloud_optics\mo_cloud_sampling.F90
 - [ ] --  312      extensions\mo_rrtmgp_clr_all_sky.F90
 - [x] --  620      extensions\cloud_optics\mo_cloud_optics.F90

**Comment by charleskawczynski** [comment]
All of the code that is tested in the original repo has been translated. Closing this for now.
